# Generated by Django 4.1.2 on 2022-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(db_index=True, upload_to='portfolio/images/', verbose_name='Изображение')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
