# Generated by Django 4.1.2 on 2022-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Название')),
                ('score', models.IntegerField(blank=True, db_index=True, default=70)),
            ],
        ),
    ]
